In [1]:
import pandas as pd
import numpy as np
import mysql.connector
from sqlalchemy import create_engine
import MySQLdb

<h3>1. Create an sqlalchemy engine using a sample from the data set</h3>

In [7]:
conn = create_engine("mysql+pymysql://{user}:{pw}@localhost/{db}"
                       .format(user="root",
                               pw="",
                               db="sqldb"))
columns = ["age","workclass","fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","income"]
datset=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data", names=columns)
df=pd.DataFrame(datset)

In [10]:
df.to_sql(name="adult", con=conn, if_exists = 'replace', index=False)

In [11]:
Rdata = pd.read_sql('SELECT * FROM adult limit 10', conn)
Rdata

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K

In [16]:
df.income.unique()

array([' <=50K', ' >50K'], dtype=object)

<h3>2. Write two basic update queries</h3>

In [34]:
conn.execute("update adult set income='1' where income=' <=50K'")

In [27]:
conn.execute("update adult set income='2' where income=' >50K'")

In [31]:
dbdf=pd.read_sql('SELECT * FROM adult', conn)

In [32]:
dbdf.income.unique()

array(['1', '2'], dtype=object)

<h3>3. Write two delete queries</h3>

In [36]:
dbdf.size

488415

In [37]:
conn.execute("delete from adult where fnlwgt='77516'")

In [38]:
dbdf=pd.read_sql('SELECT * FROM adult', conn)
dbdf.size

488400

In [42]:
dbdf["education"].unique()

array([' Bachelors', ' HS-grad', ' 11th', ' Masters', ' 9th',
       ' Some-college', ' Assoc-acdm', ' Assoc-voc', ' 7th-8th',
       ' Doctorate', ' Prof-school', ' 5th-6th', ' 10th', ' 1st-4th',
       ' Preschool', ' 12th'], dtype=object)

In [43]:
conn.execute("delete from adult where education=' 1st-4th'")

In [44]:
dbdf1=pd.read_sql('SELECT * FROM adult', conn)
dbdf1.size

485880

<h3>4. Write two filter queries</h3>

In [47]:
pd.read_sql("SELECT * FROM adult where education=' 10th'", conn)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,67,?,212759,10th,6,Married-civ-spouse,?,Husband,White,Male,0,0,2,United-States,1
1,17,?,304873,10th,6,Never-married,?,Own-child,White,Female,34095,0,32,United-States,1
2,25,Private,255004,10th,6,Never-married,Craft-repair,Not-in-family,White,Male,0,0,40,United-States,1
3,60,?,24215,10th,6,Divorced,?,Not-in-family,Amer-Indian-Eskimo,Female,0,0,10,United-States,1
4,59,Local-gov,171328,10th,6,Widowed,Other-service,Unmarried,Black,Female,0,0,30,United-States,1
5,55,Local-gov,98545,10th,6,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,1
6,36,Private,348022,10th,6,Married-civ-spouse,Other-service,Wife,White,Female,0,0,24,United-States,1
7,33,Private,228528,10th,6,Never-married,Craft-repair,Unmarried,White,Female,0,0,35,United-States,1
8,27,Private,161155,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,40,United-States,1
9,58,Private,51662,10th,6,Married-civ-spouse,Other-service,Wife,White,Female,0,0,8,United-States,1
10,52,Private,25826,10th,6,Married-civ-spouse,Craft-repair,Husband,White,Male,0,1887,47,United-States,2
11,17,Private,169658,10th,6,Never-married,Other-service,Own-child,White,Female,0,0,21,United-States,1
12,49,Local-gov,120451,10th,6,Separated,Other-service,Unmarried,Black,Female,0,0,40,United-States,1
13,58,Self-emp-not-inc,87510,10th,6,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,1
14,32,Private,283268,10th,6,Separated,Other-service,Unmarried,White,Female,0,0,42,United-States,1
15,17,Private,32607,10th,6,Never-married,Farming-fishing,Own-child,White,Male,0,0,20,United-States,1
16,21,Private,62339,10th,6,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,1
17,53,Self-emp-not-inc,311020,10th,6,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,60,United-States,1
18,41,Private,239683,10th,6,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,30,?,1
19,33,Local-gov,298785,10th,6,Divorced,Transport-moving,Not-in-family,White,Male,0,0,40,United-States,1
20,36,Private,526968,10th,6,Divorced,Exec-managerial,Unmarried,White,Female,0,0,40,United-States,1
21,48,Private,207848,10th,6,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,40,United-States,1
22,62,Private,92178,10th,6,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,1
23,57,Private,182062,10th,6,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,United-States,1
24,17,?,138507,10th,6,Never-married,?,Own-child,White,Male,0,0,20,United-States,1
25,40,Private,155190,10th,6,Never-married,Craft-repair,Other-relative,Black,Male,0,0,55,United-States,1
26,20,Private,444554,10th,6,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,40,United-States,1
27,43,Private,238287,10th,6,Never-married,Machine-op-inspct,Not-in-family,Black,Male,0,0,40,United-States,1
28,42,Private,230624,10th,6,Never-married,Transport-moving,Unmarried,White,Male,0,0,40,United-States,2
29,51,Private,246519,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,2105,0,45,United-States,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903,67,Self-emp-inc,112318,10th,6,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,1
904,29,Private,200468,10th,6,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,40,United-States,1
905,28,Private,204516,10th,6,Never-married,Transport-moving,Not-in-family,White,Male,0,0,45,United-States,1
906,52,Private,173987,10th,6,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,1
907,39,Private,226374,10th,6,Divorced,Other-service,Unmarried,Black,Female,0,0,40,United-States,1
908,56,?,119254,10th,6,Divorced,?,Not-in-family,White,Female,0,0,40,United-States,1
909,18,Private,37720,10th,6,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,40,United-States,1
910,17,Private,309504,10th,6,Never-married,Sales,Unmarried,White,Female,0,0,24,United-States,1
911,31,Private,182237,10th,6,Separated,Transport-moving,Unmarried,White,Male,0,0,40,United-States,1
912,17,?,171461,10th,6,Never-married,?,Own-child,White,Female,0,0,20,United-States,1
913,17,?,256173,10th,6,Never-married,?,Own-child,White,Female,0,0,15,United-States,1
914,18,Private,157273,10th,6,Never-married,Other-service,Other-relative,Black,Male,0,0,15,United-States,1
915,36,Private,128876,10th,6,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,1
916,34,Private,164280,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,40,Portugal,1
917,55,Private,100054,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,40,United-States,1
918,34,Private,111589,10th,6,Never-married,Other-service,Unmarried,Black,Female,0,0,40,Jamaica,1
919,56,Private,134153,10th,6,Married-civ-spouse,Adm-clerical,Husband,Black,Male,0,0,40,United-States,1
920,41,Private,151736,10th,6,Never-married,Machine-op-inspct,Not-in-family,White,Male,0,0,40,United-States,1
921,58,Private,250206,10th,6,Married-civ-spouse,Craft-repair,Husband,White,Male,5178,0,40,United-States,2
922,68,Private,274096,10th,6,Divorced,Transport-moving,Not-in-family,White,Male,0,0,20,United-States,1
923,63,Private,37792,10th,6,Widowed,Other-service,Not-in-family,White,Female,0,0,31,United-States,1
924,36,Private,43712,10th,6,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,1
925,31,Private,254304,10th,6,Divorced,Craft-repair,Not-in-family,White,Male,0,0,38,United-States,1
926,36,Private,184655,10th,6,Divorced,Transport-moving,Unmarried,White,Male,0,0,48,United-States,1
927,17,Private,117798,10th,6,Never-married,Other-service,Own-child,White,Male,0,0,20,United-States,1
928,33,Private,182401,10th,6,Never-married,Adm-clerical,Not-in-family,Black,Male,0,0,40,United-States,1
929,45,Private,155093,10th,6,Divorced,Other-service,Not-in-family,Black,Female,0,0,38,Dominican-Republic,1
930,66,Federal-gov,47358,10th,6,Married-civ-spouse,Craft-repair,Husband,White,Male,3471,0,40,United-States,1
931,32,Private,211349,10th,6,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,1
932,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,1

In [48]:
pd.read_sql("SELECT * FROM adult where education=' 10th' and age<=20", conn)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,17,?,304873,10th,6,Never-married,?,Own-child,White,Female,34095,0,32,United-States,1
1,17,Private,169658,10th,6,Never-married,Other-service,Own-child,White,Female,0,0,21,United-States,1
2,17,Private,32607,10th,6,Never-married,Farming-fishing,Own-child,White,Male,0,0,20,United-States,1
3,17,?,138507,10th,6,Never-married,?,Own-child,White,Male,0,0,20,United-States,1
4,20,Private,444554,10th,6,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,40,United-States,1
5,17,?,333100,10th,6,Never-married,?,Own-child,White,Male,1055,0,30,United-States,1
6,17,Private,163494,10th,6,Never-married,Sales,Own-child,White,Male,0,0,30,United-States,1
7,17,Private,130806,10th,6,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,24,United-States,1
8,17,?,158762,10th,6,Never-married,?,Own-child,White,Female,0,0,20,United-States,1
9,17,?,228373,10th,6,Never-married,?,Own-child,White,Male,0,0,30,United-States,1
10,17,Self-emp-not-inc,60116,10th,6,Never-married,Adm-clerical,Own-child,White,Male,0,0,10,United-States,1
11,17,Private,329783,10th,6,Never-married,Sales,Other-relative,White,Female,0,0,10,United-States,1
12,20,?,121313,10th,6,Never-married,?,Own-child,White,Male,0,0,40,United-States,1
13,20,Private,171398,10th,6,Never-married,Sales,Not-in-family,Other,Male,0,0,40,United-States,1
14,19,Private,446219,10th,6,Never-married,Sales,Unmarried,Black,Female,0,0,40,United-States,1
15,18,Private,80616,10th,6,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,27,United-States,1
16,18,Private,387568,10th,6,Never-married,Sales,Own-child,White,Male,0,0,10,United-States,1
17,17,?,179715,10th,6,Never-married,?,Own-child,White,Male,0,0,40,United-States,1
18,17,Private,139183,10th,6,Never-married,Sales,Own-child,White,Female,0,0,15,United-States,1
19,17,Private,263746,10th,6,Never-married,Other-service,Own-child,White,Male,0,0,24,United-States,1
20,17,Private,130125,10th,6,Never-married,Other-service,Own-child,Amer-Indian-Eskimo,Female,1055,0,20,United-States,1
21,17,Private,57324,10th,6,Never-married,Other-service,Own-child,White,Male,0,0,30,United-States,1
22,17,?,139183,10th,6,Never-married,?,Own-child,White,Female,0,0,15,United-States,1
23,17,Private,137042,10th,6,Never-married,Prof-specialty,Own-child,White,Male,0,0,20,United-States,1
24,18,Never-worked,206359,10th,6,Never-married,?,Own-child,White,Male,0,0,40,United-States,1
25,17,Private,327434,10th,6,Never-married,Sales,Own-child,White,Male,0,0,20,United-States,1
26,18,?,23233,10th,6,Never-married,?,Own-child,White,Male,0,0,40,United-States,1
27,19,Self-emp-not-inc,30800,10th,6,Married-spouse-absent,Adm-clerical,Unmarried,Amer-Indian-Eskimo,Female,0,0,40,United-States,1
28,18,?,279288,10th,6,Never-married,?,Other-relative,White,Female,0,0,30,United-States,1
29,19,Private,129620,10th,6,Never-married,Other-service,Other-relative,White,Female,0,0,30,United-States,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,17,Private,244523,10th,6,Never-married,Other-service,Own-child,White,Male,0,0,20,United-States,1
178,17,?,341395,10th,6,Never-married,?,Own-child,Black,Male,0,0,20,United-States,1
179,17,Private,317702,10th,6,Never-married,Sales,Own-child,Black,Female,0,0,15,United-States,1
180,17,Private,36877,10th,6,Never-married,Sales,Own-child,White,Female,0,0,10,United-States,1
181,17,Private,228253,10th,6,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,10,United-States,1
182,19,Private,283945,10th,6,Never-married,Handlers-cleaners,Other-relative,White,Male,0,1602,45,United-States,1
183,17,Private,147069,10th,6,Never-married,Sales,Own-child,White,Female,0,0,16,United-States,1
184,18,Private,34125,10th,6,Never-married,Other-service,Own-child,White,Female,0,0,28,United-States,1
185,17,Private,217342,10th,6,Never-married,Sales,Own-child,White,Female,0,0,5,United-States,1
186,18,?,387871,10th,6,Never-married,?,Own-child,White,Male,0,0,30,United-States,1
187,17,Local-gov,39815,10th,6,Never-married,Other-service,Own-child,White,Female,0,0,25,United-States,1
188,18,Private,152044,10th,6,Never-married,Other-service,Own-child,White,Female,0,0,3,United-States,1
189,17,Private,136363,10th,6,Never-married,Other-service,Own-child,White,Male,0,0,20,United-States,1
190,19,Private,199480,10th,6,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,25,United-States,1
191,17,Private,112795,10th,6,Never-married,Other-service,Own-child,White,Female,0,0,15,United-States,1
192,17,Private,132680,10th,6,Never-married,Other-service,Own-child,White,Female,0,1602,10,United-States,1
193,17,?,34019,10th,6,Never-married,?,Own-child,White,Male,0,0,20,United-States,1
194,17,Private,128617,10th,6,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,26,United-States,1
195,18,Private,337046,10th,6,Never-married,Other-service,Own-child,White,Male,0,0,40,United-States,1
196,17,?,371316,10th,6,Never-married,?,Own-child,White,Male,0,0,25,United-States,1
197,20,Private,130840,10th,6,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,40,United-States,1
198,17,Private,79682,10th,6,Never-married,Priv-house-serv,Other-relative,White,Male,0,0,30,United-States,1
199,17,Private,160049,10th,6,Never-married,Other-service,Own-child,White,Female,0,0,12,United-States,1
200,17,?,172145,10th,6,Never-married,?,Own-child,Black,Female,0,0,40,United-States,1
201,18,Private,37720,10th,6,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,40,United-States,1
202,17,Private,309504,10th,6,Never-married,Sales,Unmarried,White,Female,0,0,24,United-States,1
203,17,?,171461,10th,6,Never-married,?,Own-child,White,Female,0,0,20,United-States,1
204,17,?,256173,10th,6,Never-married,?,Own-child,White,Female,0,0,15,United-States,1
205,18,Private,157273,10th,6,Never-married,Other-service,Other-relative,Black,Male,0,0,15,United-States,1
206,17,Private,117798,10th,6,Never-married,Other-service,Own-child,White,Male,0,0,20,United-States,1